/**
 * The flows that matter (#17), against the real production build.
 *
 * The puzzle is generated by the app, not injected: there is no test-only seam
 * in the bundle, and a seam is not needed — the board is readable from the DOM,
 * and the test solves it with the same engine the app ships. That keeps the
 * production bundle the thing under test, and it means a generator that starts
 * emitting unsolvable puzzles fails here rather than passing quietly.
 *
 * One puzzle, one page, steps in order: generation is the slowest thing the app
 * does, and paying for it once per browser is the difference between a suite
 * that runs on every push and one that gets skipped.
 */

import { expect, test, type Page } from '@playwright/test';
import { Board } from '../../src/engine/board';
import { firstFinding, solveBruteForce } from '../../src/engine/solver';
import type { Digit } from '../../src/engine/types';

test.describe.configure({ mode: 'serial' });

interface DomCell {
  index: number;
  given: boolean;
  value: number | null;
  notes: number[];
}

/** The board as the player sees it, read back out of the grid. */
async function readBoard(page: Page): Promise<DomCell[]> {
  return page.locator('[data-cell]').evaluateAll((nodes) =>
    nodes
      .map((node) => {
        const element = node as HTMLElement;
        const digit = element.querySelector('span.digit')?.textContent?.trim() ?? '';
        const label = element.getAttribute('aria-label') ?? '';
        // "r3c4, empty, notes 1, 4, 9" — and possibly a sentence after it about
        // the ones a placement has killed, which is not part of the list.
        const listed = /notes ([\d,\s]+)/.exec(label)?.[1] ?? '';
        const notes = listed
          .split(',')
          .map((part) => Number(part.trim()))
          .filter((n) => n >= 1 && n <= 9);
        return {
          index: Number(element.dataset.cell),
          given: element.hasAttribute('data-given'),
          value: digit === '' ? null : Number(digit),
          notes,
        };
      })
      .sort((a, b) => a.index - b.index),
  );
}

/** True when two cells share a row, a column or a box. */
function sees(a: number, b: number): boolean {
  if (a === b) return false;
  const [ra, ca] = [Math.floor(a / 9), a % 9];
  const [rb, cb] = [Math.floor(b / 9), b % 9];
  return (
    ra === rb ||
    ca === cb ||
    (Math.floor(ra / 3) === Math.floor(rb / 3) && Math.floor(ca / 3) === Math.floor(cb / 3))
  );
}

/** A digit not yet placed anywhere `cell` can see, so noting it is legal. */
function pickAbsentDigit(cells: DomCell[], cell: number): number {
  const seen = new Set(
    cells.filter((other) => sees(cell, other.index)).map((other) => other.value),
  );
  for (let digit = 1; digit <= 9; digit++) if (!seen.has(digit)) return digit;
  throw new Error('no digit is free for that cell');
}

async function enter(page: Page, cell: number, digit: number): Promise<void> {
  await page.locator(`[data-cell="${cell}"]`).click();
  await page.keyboard.press(String(digit));
}

async function startEasyGame(page: Page): Promise<void> {
  await page.goto('/');
  await page.getByRole('button', { name: 'New puzzle' }).click();
  await page.getByRole('button', { name: 'Easy', exact: true }).click();
  // Generation runs in a worker and retries until the rating matches.
  await expect(page.getByRole('grid')).toBeVisible({ timeout: 60_000 });
}

/**
 * The coach rests as a button on a phone; the panel is behind it. On a wide
 * viewport the panel is already the static bar and the FAB never renders, so
 * the click is skipped rather than attempted against a hidden element.
 */
async function openCoach(page: Page) {
  const fab = page.getByRole('button', { name: /^Coach/ });
  if (await fab.isVisible()) await fab.click();
  return page.getByRole('region', { name: 'Coach' });
}

test.describe('one puzzle, end to end', () => {
  test('generates a puzzle and opens it on the board', async ({ page }) => {
    await startEasyGame(page);

    const cells = await readBoard(page);
    expect(cells).toHaveLength(81);
    expect(cells.filter((cell) => cell.given).length).toBeGreaterThan(16);
    await expect(page.getByRole('timer')).toBeVisible();
  });

  test('climbs the disclosure ladder one rung at a time', async ({ page }) => {
    await startEasyGame(page);
    const coach = await openCoach(page);

    // Nothing is disclosed until the player asks (R7). The ladder itself only
    // appears once there is a rung to be on — on a phone it is board otherwise.
    await expect(coach.getByRole('button', { name: 'Where should I look?' })).toBeVisible();
    await expect(coach.getByText(/Hidden single|Naked single/)).toHaveCount(0);

    await coach.getByRole('button', { name: 'Where should I look?' }).click();
    await expect(coach.getByLabel('Disclosure level 1 of 4')).toBeVisible();

    await coach.getByRole('button', { name: /Name the technique/ }).click();
    await expect(coach.getByLabel('Disclosure level 2 of 4')).toBeVisible();

    await coach.getByRole('button', { name: /Show me the cells/ }).click();
    await expect(coach.getByLabel('Disclosure level 3 of 4')).toBeVisible();
  });

  test('checks the notes the player made, and changes none of them', async ({ page }) => {
    await startEasyGame(page);
    const before = await readBoard(page);

    // A mark that is certainly wrong: a digit already placed in a peer. Any
    // empty cell with a filled peer will do — which row that turns out to be is
    // the generator's business, not the test's.
    const pair = before
      .filter((cell) => !cell.given && cell.value === null)
      .flatMap((cell) => {
        const peer = before.find((other) => sees(cell.index, other.index) && other.value !== null);
        return peer === undefined ? [] : [{ cell: cell.index, digit: peer.value as Digit }];
      })[0]!;

    await page.getByRole('button', { name: 'Notes off' }).click();
    await enter(page, pair.cell, pair.digit);

    const coach = await openCoach(page);
    await coach.getByRole('button', { name: 'Check my notes' }).click();
    await expect(coach.getByText(/need a second look/)).toBeVisible();

    // R8: the review reports, it never corrects.
    const after = await readBoard(page);
    expect(after[pair.cell].notes).toContain(pair.digit);
  });

  test('survives being killed mid-game, undo history included (R5)', async ({ page }) => {
    await startEasyGame(page);
    const start = await readBoard(page);
    const blanks = start.filter((cell) => !cell.given && cell.value === null).slice(0, 3);

    for (const cell of blanks) await enter(page, cell.index, 5);
    const played = await readBoard(page);

    // The store autosaves on a debounce; a reload is the honest way to wait for
    // it, because a game that only survives a graceful exit has not survived.
    await page.waitForTimeout(1500);
    await page.reload();
    await expect(page.getByRole('grid')).toBeVisible();

    expect(await readBoard(page)).toEqual(played);

    // The move log came back with the board: undo still walks it backwards.
    await page.getByRole('button', { name: 'Undo' }).click();
    const undone = await readBoard(page);
    expect(undone[blanks[2].index].value).toBeNull();

    await page.getByRole('button', { name: 'Redo' }).click();
    expect(await readBoard(page)).toEqual(played);
  });

  test('flags the notes a placement killed, and clears them on request', async ({ page }) => {
    await startEasyGame(page);
    const start = await readBoard(page);

    // Note a digit in an empty cell, then place that same digit in one of its
    // peers: the note is now dead by the rules, and nothing but the player's
    // own move made it so.
    const empty = start.find((cell) => !cell.given && cell.value === null)!;
    const peer = start.find(
      (cell) => !cell.given && cell.value === null && sees(empty.index, cell.index),
    )!;
    const digit = pickAbsentDigit(start, empty.index);

    await page.getByRole('button', { name: 'Notes off' }).click();
    await enter(page, empty.index, digit);
    await page.getByRole('button', { name: 'Notes on' }).click();
    await enter(page, peer.index, digit);

    // Flagged on the board, and said in words for anyone not reading colour.
    await expect(page.locator(`[data-cell="${empty.index}"] [data-stale]`)).toHaveCount(1);
    await expect(page.locator(`[data-cell="${empty.index}"]`)).toHaveAttribute(
      'aria-label',
      new RegExp(`Notes ${digit} can no longer be true here`),
    );

    // One press to clear, one undo to get them back: the marks stay the
    // player's either way. The button lives in the coach panel now, so it is
    // behind the same FAB as the rest of the coach on a phone.
    const coach = await openCoach(page);
    await coach.getByRole('button', { name: /Clear \d+ dead notes?/ }).click();
    expect((await readBoard(page))[empty.index].notes).toEqual([]);

    // The sheet is a real modal on a phone (R against a keyboard trap) and
    // sits over the keypad while open, so the keypad's own Undo has to be
    // reached the way a player would: close the sheet first. Escape is a
    // no-op on the desktop bar, where the keypad was never covered.
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'Undo' }).click();
    expect((await readBoard(page))[empty.index].notes).toEqual([digit]);
  });

  test('the green highlight survives moving the caret', async ({ page }) => {
    await startEasyGame(page);

    // Any digit a given already carries is guaranteed to light something up;
    // the puzzle's own givens are what makes the choice safe rather than
    // hardcoding a digit that might not appear on this board at all.
    const digit = (await readBoard(page)).find((cell) => cell.given)!.value as Digit;

    // Arming does not need a selected cell at all — the keypad owns this
    // state now, not the selection (R3).
    await page.getByRole('button', { name: `Place ${digit}` }).click();
    const lit = page.locator('[role="gridcell"][data-match="true"]');
    await expect(lit.first()).toBeVisible();
    const before = await lit.count();

    // Moving the caret is not a tap that writes anything, so it must leave
    // the highlight exactly as it was.
    await page.getByRole('gridcell', { name: /r5c5/ }).click();
    await expect(lit).toHaveCount(before);
  });

  test('plays a puzzle through to the end', async ({ page }) => {
    await startEasyGame(page);
    const cells = await readBoard(page);

    const values = cells.map((cell) => (cell.value === null ? null : (cell.value as Digit)));
    const solution = solveBruteForce(Board.fromValues(values));
    expect(solution, 'the generated puzzle must be solvable').not.toBeNull();

    for (const cell of cells) {
      if (cell.value !== null) continue;
      await enter(page, cell.index, solution!.values[cell.index]!);
    }

    await expect(page.getByText('Solved', { exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'New game' })).toBeVisible();

    // The recap reports what the coach was asked for. This puzzle was solved
    // from the solution, so the honest answer is "nothing".
    await expect(page.getByText(/without asking the coach anything/)).toBeVisible();

    // And a solved board belongs under Finished, not under In progress.
    await page.getByRole('button', { name: 'Your games' }).click();
    await expect(page.getByText('Finished')).toBeVisible();
    await expect(page.getByText(/Finished in \d/)).toBeVisible();
    await expect(page.getByText('Nothing on the desk')).toBeVisible();
  });
});

test.describe('drills', () => {
  test('sets a challenge, and confirms it only when the board shows it', async ({ page }) => {
    await startEasyGame(page);
    let coach = await openCoach(page);

    await coach.getByRole('button', { name: 'Set me a challenge' }).click();
    await expect(coach.getByText(/There is a .* on this board/)).toBeVisible();

    // An easy board's first finding is a single, so applying it is placing
    // the digit it proves — read with the same engine call the app itself
    // makes (`nextFinding` is `firstFinding` over exactly this board), not by
    // guessing which cell the drill meant.
    const cells = await readBoard(page);
    const values = cells.map((cell) => (cell.value === null ? null : (cell.value as Digit)));
    const board = Board.fromValues(values);
    const solution = solveBruteForce(board);
    expect(solution).not.toBeNull();
    const finding = firstFinding(board);
    expect(finding).not.toBeNull();

    const spotlight = page.locator('[data-spotlight]');
    // Nothing is spotlighted by a level-2 disclosure: the technique is named,
    // the cells are not (R7).
    await expect(spotlight).toHaveCount(0);

    // The sheet is a real modal on a phone and sits over the board while
    // open, so touching a cell means closing it first — the same trade a
    // player makes. `Escape` is a no-op on the desktop bar, which never
    // covered the board in the first place.
    await page.keyboard.press('Escape');

    // A wrong move does not satisfy a drill.
    const empty = cells.find((cell) => cell.value === null)!;
    const wrong = ((solution!.values[empty.index]! % 9) + 1) as Digit;
    await enter(page, empty.index, wrong);
    coach = await openCoach(page);
    await expect(coach.getByText(/applied by you/)).toHaveCount(0);
    await page.keyboard.press('Escape');
    await page.locator(`[data-cell="${empty.index}"]`).click();
    await page.keyboard.press('Backspace');

    // Only the cell(s) the finding itself places, not the rest of the board:
    // filling every remaining cell would solve the puzzle outright, and a
    // solved game covers the FAB with its own "Solved" sheet before this
    // could reopen the coach to read it. Placing just the finding's own
    // digit is also the more exact proof — it is the move the drill is
    // actually about, not an accident of finishing the grid.
    for (const { cell, digit } of finding!.placements) {
      await enter(page, cell, digit);
    }

    coach = await openCoach(page);
    await expect(coach.getByText(/applied by you/)).toBeVisible();
  });
});

test.describe('the keyboard', () => {
  test('plays the game without the mouse', async ({ page }) => {
    await startEasyGame(page);
    const cells = await readBoard(page);
    const empty = cells.find((cell) => !cell.given && cell.value === null)!;

    // N is notes mode, so the same keystroke writes a mark rather than a digit.
    await page.keyboard.press('n');
    await expect(page.getByRole('group', { name: 'Keypad, notes mode' })).toBeVisible();
    await enter(page, empty.index, 4);
    expect((await readBoard(page))[empty.index].notes).toEqual([4]);

    await page.keyboard.press('n');
    await enter(page, empty.index, 4);
    expect((await readBoard(page))[empty.index].value).toBe(4);

    // U and R walk the same history the buttons do.
    await page.keyboard.press('u');
    expect((await readBoard(page))[empty.index].value).toBeNull();
    await page.keyboard.press('r');
    expect((await readBoard(page))[empty.index].value).toBe(4);

    // And the shortcut every player tries first.
    await page.keyboard.press('ControlOrMeta+z');
    expect((await readBoard(page))[empty.index].value).toBeNull();

    // 'h' opens the sheet itself on a narrow viewport (it is how a keyboard
    // player reaches a coach that a mouse would tap the FAB for) — a direct
    // query here, not `openCoach`, because that helper's own eager
    // `isVisible()` read on the FAB can land in the instant between the
    // keypress and React committing `sheetOpen`, where the FAB is still
    // mid-transition; `toBeVisible`'s own retrying is what the FAB's minimal
    // fixed-membership guard cannot offer.
    await page.keyboard.press('h');
    const coach = page.getByRole('region', { name: 'Coach' });
    await expect(coach.getByLabel('Disclosure level 1 of 4')).toBeVisible();
  });
});
