/**
 * The flows that matter (#17), against the real production build.
 *
 * The puzzle is generated by the app, not injected: there is no test-only seam
 * in the bundle, and a seam is not needed — the board is readable from the DOM,
 * and the test solves it with the same engine the app ships. That keeps the
 * production bundle the thing under test, and it means a generator that starts
 * emitting unsolvable puzzles fails here rather than passing quietly.
 *
 * One puzzle, one page, steps in order: generation is the slowest thing the app
 * does, and paying for it once per browser is the difference between a suite
 * that runs on every push and one that gets skipped.
 */

import { expect, test, type Page } from '@playwright/test';
import { Board } from '../../src/engine/board';
import { solveBruteForce } from '../../src/engine/solver';
import type { Digit } from '../../src/engine/types';

test.describe.configure({ mode: 'serial' });

interface DomCell {
  index: number;
  given: boolean;
  value: number | null;
  notes: number[];
}

/** The board as the player sees it, read back out of the grid. */
async function readBoard(page: Page): Promise<DomCell[]> {
  return page.locator('[data-cell]').evaluateAll((nodes) =>
    nodes
      .map((node) => {
        const element = node as HTMLElement;
        const digit = element.querySelector('span.digit')?.textContent?.trim() ?? '';
        const label = element.getAttribute('aria-label') ?? '';
        const notes = label.includes('notes')
          ? label
              .slice(label.indexOf('notes') + 5)
              .split(',')
              .map((part) => Number(part.trim()))
              .filter((n) => n >= 1 && n <= 9)
          : [];
        return {
          index: Number(element.dataset.cell),
          given: element.hasAttribute('data-given'),
          value: digit === '' ? null : Number(digit),
          notes,
        };
      })
      .sort((a, b) => a.index - b.index),
  );
}

async function enter(page: Page, cell: number, digit: number): Promise<void> {
  await page.locator(`[data-cell="${cell}"]`).click();
  await page.keyboard.press(String(digit));
}

async function startEasyGame(page: Page): Promise<void> {
  await page.goto('/');
  await page.getByRole('button', { name: 'New puzzle' }).click();
  await page.getByRole('button', { name: 'Easy', exact: true }).click();
  // Generation runs in a worker and retries until the rating matches.
  await expect(page.getByRole('grid')).toBeVisible({ timeout: 60_000 });
}

test.describe('one puzzle, end to end', () => {
  test('generates a puzzle and opens it on the board', async ({ page }) => {
    await startEasyGame(page);

    const cells = await readBoard(page);
    expect(cells).toHaveLength(81);
    expect(cells.filter((cell) => cell.given).length).toBeGreaterThan(16);
    expect(page.getByRole('timer')).toBeVisible();
  });

  test('climbs the disclosure ladder one rung at a time', async ({ page }) => {
    await startEasyGame(page);
    const coach = page.getByRole('region', { name: 'Coach' });

    // Nothing is disclosed until the player asks (R7).
    await expect(coach.getByLabel('Disclosure level 0 of 4')).toBeVisible();

    await coach.getByRole('button', { name: 'Where should I look?' }).click();
    await expect(coach.getByLabel('Disclosure level 1 of 4')).toBeVisible();

    await coach.getByRole('button', { name: /Name the technique/ }).click();
    await expect(coach.getByLabel('Disclosure level 2 of 4')).toBeVisible();

    await coach.getByRole('button', { name: /Show me the cells/ }).click();
    await expect(coach.getByLabel('Disclosure level 3 of 4')).toBeVisible();
  });

  test('checks the notes the player made, and changes none of them', async ({ page }) => {
    await startEasyGame(page);
    const before = await readBoard(page);
    const empty = before.find((cell) => !cell.given && cell.value === null)!;

    // Notes mode, then a mark that is certainly wrong: a digit already placed
    // in the same row.
    const rowStart = Math.floor(empty.index / 9) * 9;
    const placed = before
      .slice(rowStart, rowStart + 9)
      .find((cell) => cell.value !== null)!.value as Digit;

    await page.getByRole('button', { name: 'Notes off' }).click();
    await enter(page, empty.index, placed);

    const coach = page.getByRole('region', { name: 'Coach' });
    await coach.getByRole('button', { name: 'Check my notes' }).click();
    await expect(coach.getByText(/need a second look/)).toBeVisible();

    // R8: the review reports, it never corrects.
    const after = await readBoard(page);
    expect(after[empty.index].notes).toContain(placed);
  });

  test('survives being killed mid-game, undo history included (R5)', async ({ page }) => {
    await startEasyGame(page);
    const start = await readBoard(page);
    const blanks = start.filter((cell) => !cell.given && cell.value === null).slice(0, 3);

    for (const cell of blanks) await enter(page, cell.index, 5);
    const played = await readBoard(page);

    // The store autosaves on a debounce; a reload is the honest way to wait for
    // it, because a game that only survives a graceful exit has not survived.
    await page.waitForTimeout(1500);
    await page.reload();
    await expect(page.getByRole('grid')).toBeVisible();

    expect(await readBoard(page)).toEqual(played);

    // The move log came back with the board: undo still walks it backwards.
    await page.getByRole('button', { name: 'Undo' }).click();
    const undone = await readBoard(page);
    expect(undone[blanks[2].index].value).toBeNull();

    await page.getByRole('button', { name: 'Redo' }).click();
    expect(await readBoard(page)).toEqual(played);
  });

  test('fills every note on request, and takes one undo to take it back', async ({ page }) => {
    await startEasyGame(page);

    // A mark of the player's own first, so the fill has something to replace
    // and the confirmation has something to be about.
    const start = await readBoard(page);
    const empty = start.find((cell) => !cell.given && cell.value === null)!;
    await page.getByRole('button', { name: 'Notes off' }).click();
    await enter(page, empty.index, 5);

    await page.getByRole('button', { name: 'Fill in every note' }).click();
    await page.getByRole('button', { name: 'Fill in every note' }).last().click();

    const filled = await readBoard(page);
    const blanks = filled.filter((cell) => cell.value === null);
    expect(blanks.every((cell) => cell.notes.length > 0)).toBe(true);

    // One batch, one undo (R4): the whole fill comes back off in a single press.
    await page.getByRole('button', { name: 'Undo' }).click();
    const undone = await readBoard(page);
    expect(undone.filter((cell) => cell.notes.length > 0)).toHaveLength(1);
    expect(undone[empty.index].notes).toEqual([5]);
  });

  test('plays a puzzle through to the end', async ({ page }) => {
    await startEasyGame(page);
    const cells = await readBoard(page);

    const values = cells.map((cell) => (cell.value === null ? null : (cell.value as Digit)));
    const solution = solveBruteForce(Board.fromValues(values));
    expect(solution, 'the generated puzzle must be solvable').not.toBeNull();

    for (const cell of cells) {
      if (cell.value !== null) continue;
      await enter(page, cell.index, solution!.values[cell.index]!);
    }

    await expect(page.getByText('Solved', { exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'New game' })).toBeVisible();

    // The recap reports what the coach was asked for. This puzzle was solved
    // from the solution, so the honest answer is "nothing".
    await expect(page.getByText(/without asking the coach anything/)).toBeVisible();

    // And a solved board belongs under Finished, not under In progress.
    await page.getByRole('button', { name: 'Your games' }).click();
    await expect(page.getByText('Finished')).toBeVisible();
    await expect(page.getByText(/Finished in \d/)).toBeVisible();
    await expect(page.getByText('Nothing on the desk')).toBeVisible();
  });
});
